### ISSUE TITLE
Error when using expires

### ISSUE THREAD

**Issue by yadyn** [DAlperin/remix-redis-session#5]
Redis expects the expires value to be an integer, however the `expiresToSeconds` function returns values with a decimal value. As such, we get errors like this:

```
ReplyError: ERR value is not an integer or out of range
    at parseError (C:\Source\__rp\payments-web\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Source\__rp\payments-web\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'set',
    args: [
      'KEY GOES HERE',
      '{ DATA GOES HERE }',
      'EX',
      '1199.999' <-- This is the problem argument
    ]
  }
}
```

I believe the fix is to simply wrap the return with `Math.round`.

**Comment by wjstraver** [comment]
Got the same error today and I agree with your solution at https://github.com/DAlperin/remix-redis-session/pull/6

got to love floating point errors 🙂

**Comment by tpennetta** [comment]
This is unfortunately creating a broken state when using this package with Expires property. Would love to bump this to get the PR merged in.
